CREATE TABLE IF NOT EXISTS t_user (
	`uid` INT(8) UNSIGNED AUTO_INCREMENT,
	`tel` VARCHAR(11) NOT NULL,
	`password` VARCHAR(20) NOT NULL,
	`username` VARCHAR(15) NOT NULL,
	`pic` VARCHAR(100) NOT NULL,
	`sex` INT(1) NOT NULL,
	`status` INT(1) NOT NULL,
	`createtime` DATE NOT NULL,
   PRIMARY KEY (`uid`)
)AUTO_INCREMENT=10000001 DEFAULT CHARSET=utf8;