CREATE TABLE IF NOT EXISTS t_user (
	`uid` INT(8) NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(50) NOT NULL,
	`password` VARCHAR(20) NOT NULL,
	`username` VARCHAR(15) NOT NULL,
	`ip` VARCHAR(15) NOT NULL ,
	`avatar` VARCHAR(100) NOT NULL,
	`sex` INT(1) NOT NULL,
	`status` INT(1) NOT NULL,
	`createtime` DATE NOT NULL,
   PRIMARY KEY (`uid`)
)AUTO_INCREMENT=10000001 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS t_group (
	`groupid` INT(8) NOT NULL AUTO_INCREMENT,
	`groupname` VARCHAR(20) NOT NULL,
	`groupmasteruid` INT(8) NOT NULL,
	`desc` VARCHAR(200) NOT NULL,
	`createtime` DATE NOT NULL,
  PRIMARY KEY (`groupid`),
	FOREIGN KEY (`groupmasteruid`) REFERENCES t_user(`uid`)
)AUTO_INCREMENT=50000001 DEFAULT CHARSET=utf8;